server:
  port: 8002

msa:
  cart-service:
    url: localhost:8000
  product-service:
    url: localhost:8001


spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 5
      max-lifetime: 30000
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

cloud:
  aws:
    s3:
      bucket:
    region:
      static:
    cloud-front:
      domain-name:
      distribution-id:

